[data]
root = "/netscratch/mhannani/data_preparation/TED2020"

tmx_file = "ar-en.tmx"

processed = "/netscratch/mhannani/data_preparation/TED2020/processed"
index = "/netscratch/mhannani/data_preparation/TED2020/index"

source_language = "en"
target_language = "ar"

json_output = "en_ar_data.json"
faiss_path = "index/faiss_index.index"

[prompting]
source_language = "English"
target_language = "Arabic"

[fuzzy]
embedding_model_name = "sentence-transformers/all-MiniLM-L6-v2"

[results]
root = "results/TED2020"
pairs_csv = "predictions.tsv"
scores_csv = "scores.csv"
