[data]
root = "./data/open_subtitles"
raw = "./data/open_subtitles/raw"
processed = "./data/open_subtitles/processed"
index = "./data/open_subtitles/index"
source_language = "OpenSubtitles.ar-en-small.en.txt"
target_language = "OpenSubtitles.ar-en-small.ar.txt"
json_output = "data.json"
faiss_path = "index/faiss_index.index"

[prompting]
source_language = "English"
target_language = "Arabic"

[fuzzy]
embedding_model_name = "sentence-transformers/all-MiniLM-L6-v2"

[results]
root = "results/open_subtitles"
pairs_csv = "three_pairs.tsv"
scores_csv = "scores.csv"
